### ISSUE TITLE
Bug trying to edit a `package.json` with unsaved changes

### ISSUE THREAD

**Issue by pedro757** [vuki656/package-info.nvim#120]
`E5108: Error executing lua .../opt/package-info.nvim/lua/package-info/modules/core.lua:173: Vim(edit):E37
: No write since last change (add ! to override)`

You can't run `:e` on an file with unsaved changes

https://github.com/vuki656/package-info.nvim/blob/10de4d0d50ec1d4d26118c4aa067a9d09e370c9c/lua/package-info/modules/core.lua#L171-L175

**Comment by vuki656** [comment]
I'm able to reproduce this.

What do you think would be the preferred way to handle this?

Also, please follow the issue template next time.

**Comment by pedro757** [comment]
Oh sorry, I didn't know there was an issue template, if you create an issue from this button it does not show any template

![image](https://user-images.githubusercontent.com/30637426/167048308-ce857903-75b5-4033-b4a3-e4311638fea7.png)

Could I ask, what does `__reload_buffer` do? I just removed it and it works

**Comment by vuki656** [comment]
Hey, sorry for the late reply regarding this, I forgot about it.

Here is the [PR](https://github.com/vuki656/package-info.nvim/pull/85) regarding that.
