### ISSUE TITLE
[BUG]: Once a package.json is loaded, every buffer after shows that it is invalid

### ISSUE THREAD

**Issue by lmburns** [vuki656/package-info.nvim#126]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.6 neovim version or later

### Neovim Version

NVIM v0.8.0-dev+415-gdd8b6094c

### Branch

master

### Actual behavior

After the latest upgrade I've noticed two problems:

1. Every single `package.json` file I open, I get the message `PackageInfo: Not in valid package.json file`. I'm in the process of debugging this right now.
2. If a `package.json` file is opened, and then I open another file after that without closing the `package.json`, that same error message is displayed for every single buffer I enter.

A fix for number 2 would be to change the `autocmd` you have to created to be more specific than simply `BufEnter`, it could be `BufEnter` or `BufRead` with `package.json` as the pattern. To do this `package-info.utils.register-autocmd` could also use the new neovim API (i.e., `vim.api.nvim_create_augroup` and `vim.api.nvim_create_autocmd`)

### Expected behavior

The expected behavior is for the plugin to load when opening a `package.json` file and not when opening any other file.

### Steps to reproduce

Open a `package.json` file and get the error. Don't close that buffer and open any other buffer, the same error is repeatedly displayed.

### Package info config

```lua
    require("package-info").setup(
        {
            colors = {
                up_to_date = "#3C4048", -- Text color for up to date package virtual text
                outdated = "#d19a66" -- Text color for outdated package virtual text
            },
            icons = {
                enable = true, -- Whether to display icons
                style = {
                    up_to_date = "|  ", -- Icon for up to date packages
                    outdated = "|  " -- Icon for outdated packages
                }
            },
            autostart = true, -- Whether to autostart when `package.json` is opened
            hide_up_to_date = true, -- It hides up to date versions when displaying virtual text
            hide_unstable_versions = false, -- It hides unstable versions from version list e.g next-11.1.3-canary3
            -- `npm`, `yarn`
            package_manager = "yarn"
        }
    )
```

### Help

Yes

### Implementation help

I could possibly submit a pull request this evening.

**Comment by vuki656** [comment]
Fixed in [here](https://github.com/vuki656/package-info.nvim/commit/45e409c69063a057250833a747e52e2ff00dd722). Let me know if it still happens.
