### ISSUE TITLE
[FEATURE REQUEST] Support nvim-notify

### ISSUE THREAD

**Issue by ecosse3** [vuki656/package-info.nvim#131]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Hi,

it would be nice if this plugin could support [nvim-notify](https://github.com/rcarriga/nvim-notify) via a specific option. It could look like that:

![image](https://user-images.githubusercontent.com/17691791/189548948-088b2b40-8e8e-4c5c-a996-a14eb2d1af03.png)

Even displaying current npm installation progress (if possible):

![152641078-92f3da72-f49f-4705-aec8-86512693445f](https://user-images.githubusercontent.com/17691791/189549115-0f34abec-c2ec-477d-859a-29d13bcca9d3.gif)

I think it's a great addition to this plugin.

Regards

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I need time to understand how your queue works and if I need it with nvim-notify. Probably not since nvim-notify supports it somehow by default by displaying multiple notifications at once with a timeout. Will take a look in next week to implement this feature but I cannot guarantee the best code quality or tests (I've never tested with lua).

**Comment by vuki656** [comment]
Hey, that's a good idea since it works out of the box for everyone instead of relying on status bar customizability. 

Give it a go and let me know if you have any questions.

I'd be happy to help along the way.

**Comment by luisfrocha** [comment]
Any updates on this? I'd be interested in it. I'm currently trying to get the status to show up in Lualine but haven't been able to.

**Comment by vuki656** [comment]
> Any updates on this? I'd be interested in it. I'm currently trying to get the status to show up in Lualine but haven't been able to.

Hey @luisfrocha, could you paste your lualine code which didn't work? 

As for the ticket itself, im open to review a PR.

**Comment by vuki656** [comment]
Hey, could you check #143 and provide feedback?
