### ISSUE TITLE
[FEATURE REQUEST] add option to configure the order of detection of package manager

### ISSUE THREAD

**Issue by towry** [vuki656/package-info.nvim#139]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

The current detect order is ['npm', 'yarn', 'pnpm'], there should be an option to change this.

### Help

Yes

### Implementation help

I will try to implement this and submit a pull request.

**Comment by vuki656** [comment]
Hey, could you explain why this is needed? It detects them from lock files which you should never have more than 1.

**Comment by towry** [comment]
Some project may use npm but I prefer pnpm. also it seems npm wil update yarn.lock files as well.

**Comment by vuki656** [comment]
What would be the case where you would choose a different one from the initial one?

If you work alone, you can just replace it, and if you work with someone, it makes no sense to use a different one since you will have another different lock file which is not ideal.
