### ISSUE TITLE
[BUG] remove icon for `require('package-info').get_status()`

### ISSUE THREAD

**Issue by hinell** [vuki656/package-info.nvim#145]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.6 neovim version or later

### Neovim Version

NVIM v0.10.0-dev-8405649f92

### Branch

master

### Actual behavior

https://github.com/vuki656/package-info.nvim/blob/4d98c8cc90d970d87c472c04bf7ca712336cc753/lua/package-info/actions/show.lua#L27-L31
![image](https://github.com/vuki656/package-info.nvim/assets/8136158/202e351a-dd60-426e-9aa3-33757026f7c3)
I suggest to either remove icon or make it configurabe. It's not displayed properly in my setup: I'm using [nerd-fonts](https://github.com/ryanoasis/nerd-fonts)

### Expected behavior

n/a

### Steps to reproduce

n/a

### Package info config

n/a

### Help

No, sorry.

**Comment by vuki656** [comment]
Does the icon not show correctly anymore? Not sure I understand from the issue. 

Could we replace it with something else?

**Comment by hinell** [comment]
![image](https://github.com/vuki656/package-info.nvim/assets/8136158/202e351a-dd60-426e-9aa3-33757026f7c3)

The icon is missing so it's displayed like this.
