### ISSUE TITLE
[BUG] Error when key contained in dependencies and devDependencies

### ISSUE THREAD

**Issue by LandonSchropp** [vuki656/package-info.nvim#148]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.6 neovim version or later

### Neovim Version

v0.9.4

### Branch

master

### Actual behavior

I'm running into an issue when switching to a tab  an _invalid_ package.json that contains a duplicate key in `dependencies` and `devDependencies`.

```
E5108: Error executing lua: ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:143: Error executing lua: ...al/share/nvim/lazy/mi
ni.bufremove/lua/mini/bufremove.lua:152: BufEnter Autocommands for "package.json": Vim(lua):E5108: Error executing lua vim/shared.lua:0: k
ey found in more than one map: @types/react
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'tbl_extend'
        .../nvim/lazy/package-info.nvim/lua/package-info/parser.lua:12: in function 'parse_buffer'
        ...re/nvim/lazy/package-info.nvim/lua/package-info/core.lua:52: in function 'load_plugin'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_win_set_buf'
        ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:152: in function <...al/share/nvim/lazy/mini.bufremove/lua/mini/bufrem
ove.lua:143>
        [C]: in function 'nvim_win_call'
        ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:143: in function <...al/share/nvim/lazy/mini.bufremove/lua/mini/bufrem
ove.lua:133>
        vim/shared.lua: in function 'tbl_map'
        ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:119: in function 'unshow'
        ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:216: in function 'delete'
        /Users/landon/.config/nvim/lua/astronvim/utils/buffer.lua:158: in function 'close'
        /Users/landon/.config/nvim/lua/astronvim/mappings.lua:51: in function </Users/landon/.config/nvim/lua/astronvim/mappings.lua:51>
stack traceback:
        [C]: in function 'nvim_win_set_buf'
        ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:152: in function <...al/share/nvim/lazy/mini.bufremove/lua/mini/bufrem
ove.lua:143>
        [C]: in function 'nvim_win_call'
        ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:143: in function <...al/share/nvim/lazy/mini.bufremove/lua/mini/bufrem
ove.lua:133>
        vim/shared.lua: in function 'tbl_map'
        ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:119: in function 'unshow'
        ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:216: in function 'delete'
        /Users/landon/.config/nvim/lua/astronvim/utils/buffer.lua:158: in function 'close'
        /Users/landon/.config/nvim/lua/astronvim/mappings.lua:51: in function </Users/landon/.config/nvim/lua/astronvim/mappings.lua:51>
stack traceback:
        [C]: in function 'nvim_win_call'
        ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:143: in function <...al/share/nvim/lazy/mini.bufremove/lua/mini/bufrem
ove.lua:133>
        vim/shared.lua: in function 'tbl_map'
        ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:119: in function 'unshow'
        ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:216: in function 'delete'
        /Users/landon/.config/nvim/lua/astronvim/utils/buffer.lua:158: in function 'close'
        /Users/landon/.config/nvim/lua/astronvim/mappings.lua:51: in function </Users/landon/.config/nvim/lua/astronvim/mappings.lua:51>
```

### Expected behavior

Even though the package is invalid, I wouldn't expect the plugin to product an error.

### Steps to reproduce

1. Add the following package.json:
   
   ``` json
   {
     "dependencies": {
       "@types/react": "^18.2.45"
     },
     "devDependencies": {
       "@types/react": "^18"
     }
   }
   ```
2. Open the package.json buffer.
3. Open a _second_ buffer with a different file.
4. Switch back to the first buffer.

### Package info config

I'm using the AstroCommunity TypeScript pack, which [this plugin is included in](https://github.com/AstroNvim/astrocommunity/blob/5ae9eed83715c9501f1763c81e1091bc5473b12e/lua/astrocommunity/pack/typescript/init.lua#L106C1-L111).

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

If you let me know where the issue is, I can fix it. 🙂

**Comment by vuki656** [comment]
Hey, this indeed shouldn't throw.

I'm currently on vacation till the end of month and can take a look after that.

If you are up for it, try to fix it. 

I'm quite sure the problem is [here](https://github.com/vuki656/package-info.nvim/blob/18f8126dd8e65b2e21804c9107785af4abbb5bfc/lua/package-info/parser.lua#L12) as table extend is set to error if there are duplicate keys.

Not really sure what would be the best way to handle this. Maybe show a notification to a user that package json is invalid if there are multiple same name deps? What do you think?

**Comment by LandonSchropp** [comment]
No worries on the timeline—I hope you're enjoying your vacation and not spending too much time on GitHub. 😉

I'm a bit swamped myself right now, so I'm not sure if I'll be able to jump in on this one.

**Comment by nhomble** [comment]
I agree with the diagnosis @vuki656. The `tbl_extend` helps make sure we consider the dupe case. 

I propose we just pick the value from `dependencies` section over `devDependencies` because it's the 2nd arg in the merge function. I know.. it's not really scientific nor would the user know that this exists, but I'd rather other tooling (or just my build system) reject my invalid `package.json` rather than have my editor barf. 

--

In terms of feedback, I think we could just prefix the message in the `current` key. At least this seems to be the right level of feedback and (lack of) friction with my editor.
