### ISSUE TITLE
[BUG] "encoding" npm package in package.json leads to error

### ISSUE THREAD

**Issue by belafonte** [vuki656/package-info.nvim#152]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.6 neovim version or later

### Neovim Version

v0.9.4

### Branch

master

### Actual behavior

Does not start and throws BufEnter Autocommand Error, that the plugin cannot be loaded.

### Expected behavior

Should not throw the Error.

### Steps to reproduce

Add encoding npm package to package.json

https://www.npmjs.com/package/encoding

### Package info config

default

### Other information

Actually i don't know when i installed that npm package to my project...
But when adding it via npm,  package-info stops working.
After removing the "encoding" package and package-info works again.

### Help

No, sorry.

**Comment by belafonte** [comment]
Ah i just recognized, that the package was twice in the package.json, which produces the error.
My bad.

**Comment by vuki656** [comment]
Hey, thanks for letting me know. Sorry I didn't get to this earlier.

If you're up for it, might not be a bad idea to throw a user friendly error that two of the sam packages are present.

**Comment by belafonte** [comment]
Hi, no worries! I would try to fix it, if i could, but unfortunately i'am not experienced in writing lua 😬.
I also saw that the issue is already tracked here https://github.com/vuki656/package-info.nvim/issues/148
