### ISSUE TITLE
[FEATURE REQUEST] Extend functionality to Maven

### ISSUE THREAD

**Issue by EpsilonKu** [vuki656/package-info.nvim#30]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

What about to support maven and gradle? 

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by vuki656** [comment]
Hey, thanks for the suggestion.

For sure, after the core functionalities are finished I plan on supporting other langs. 

Is there a way to get a list of all outdated packages with `maven`/`grade`? For example, running a command in the terminal that would check your project and list all outdated packages.

**Comment by EpsilonKu** [comment]
Yea, `maven` can check it by `mvn versions:display-dependency-updates` command. Output looks like this:
``` 
[INFO] ------------------------------------------------------------------------
[INFO] Building Build Helper Maven Plugin
[INFO]    task-segment: [versions:display-dependency-updates]
[INFO] ------------------------------------------------------------------------
[INFO] [versions:display-dependency-updates]
[INFO]
[INFO] The following dependency updates are available:
[INFO]   org.apache.maven:maven-artifact ........................ 2.0 -> 2.0.9
[INFO]   org.apache.maven:maven-plugin-api ...................... 2.0 -> 2.0.9
[INFO]   org.apache.maven:maven-project ....................... 2.0.2 -> 2.0.9
[INFO]   org.codehaus.plexus:plexus-utils ....................... 1.1 -> 1.5.6
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17 seconds
[INFO] Finished at: Fri Aug 15 10:46:03 IST 2008
[INFO] Final Memory: 10M/167M
[INFO] ------------------------------------------------------------------------
```
Gradle can show update with additional [plugin](https://github.com/ben-manes/gradle-versions-plugin#gradle-versions-plugin). Output looks like this:
```
------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.maksim88:PasswordEditText:v0.9
 - com.marcinorlowski:webnet-log:1.0.3
 - com.nulab-inc:zxcvbn:1.2.2

The following dependencies exceed the version found at the milestone revision level:
 - com.hannesdorfmann.fragmentargs:annotation [4.0.0-SNAPSHOT <- 3.0.2]
 - com.hannesdorfmann.fragmentargs:bundler-parceler [4.0.0-SNAPSHOT <- 3.0.2]
 - com.github.bumptech.glide:glide [3.7.0 <- 3.6.1]
 - com.hannesdorfmann.fragmentargs:processor [4.0.0-SNAPSHOT <- 3.0.2]

The following dependencies have later milestone versions:
 - com.github.PhilJay:MPAndroidChart [v2.2.5 -> v3.0.1]
 - com.android.support:appcompat-v7 [25.1.0 -> 25.1.1]
 - com.jakewharton:butterknife [8.4.0 -> 8.5.1]

Generated report file build/dependencyUpdates\report.txt
```

**Comment by vuki656** [comment]
Awesome, Ill look into implementing it when I have time.

**Comment by vuki656** [comment]
Hey, unfortunately, due to time constraints I don't think I'll have time anytime soon to implement something like this. 

Also since I saw that there are similar plugins popping up for different languages I think it's better to chose a single-purpose one instead of a do it all.

Feel free to fork this plugin and adapt it for maven, I'd be happy to help with any problems that might arise.
