### ISSUE TITLE
[FEATURE REQUEST] Add commands

### ISSUE THREAD

**Issue by romgrk** [vuki656/package-info.nvim#34]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

Add commands for show & close. They're easier to map & call than having to script lua directly.

### Help

No, sorry.

**Comment by vuki656** [comment]
Hey, thanks for the suggestion.

I'm currently working on actions to add/remove/change packages.

After that is done, ill add this.
