### ISSUE TITLE
[BUG] Highlight not working on 256 color terminals

### ISSUE THREAD

**Issue by ajslater** [vuki656/package-info.nvim#35]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.5 neovim version

### Neovim Version

NVIM v0.5.0 Build type: Release LuaJIT 2.1.0-beta3 Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include

### Branch

master

### Actual behavior

If package-info.nvim is configured with:
```lua
  icons = { enable = false }
```
Then virtual text colors are not observed. The rest of the display seems fine.
Virtual text colors work fine if icons are enabled, which is the default, as i'm sure you're aware.

Tested using Terminal.app on MacOS 11.5.1

### Expected behavior

I would see the default virtual text color for outdated packages (#d19a66)  like i do when icons are enabled

### Steps to reproduce

configure package-info.nvim like so:
```lua
require('package-info').setup {
   icons = { enable = false },                                             
}
```

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

If I felt ambitious, maybe. But I reckon this might be a quick one for someone already familiar with the code.

**Comment by vuki656** [comment]
Hey, thanks for checking out the plugin.

I think I know what the problem is. I'll take care of it tomorrow morning.

**Comment by vuki656** [comment]
> Then virtual text colors are not observed. The rest of the display seems fine.

Just to be on the same page, when you say observed, you mean you get no colors at all if you disable icons?

**Comment by ajslater** [comment]
I just tried this morning and saw no color highlighting with icons enabled or disabled. Like many people I have a slew of plugins enabled so I created a new init.lua that only loads your plugin:
```lua
local cmd = vim.cmd -- Vim commands e.g. cmd('pwd')  
cmd 'packadd paq-nvim' -- load the package manager            
local paq = require('paq-nvim').paq  
paq {'savq/paq-nvim', opt = true} -- paq-nvim manages itself  
                                                              
paq {'vuki656/package-info.nvim'} -- package.json versioning  
require('package-info').setup {                               
    icons = {                                                 
        style = {
        ¦   up_to_date = "| =", -- Icon for up to date packages
        ¦   outdated = "| -", -- Icon for outdated packages       
        },                                                    
    }       
}           
                                                              
paq {'nanotech/jellybeans.vim'}  
cmd('colorscheme jellybeans')
```
And still no highlights in Terminal.app
<img width="305" alt="term app" src="https://user-images.githubusercontent.com/263494/128777477-d635a504-493b-4f89-ae8e-fae06066992f.png">

So I thought to myself, this thing might be intended to be used with truecolor, and possibly something's funky with my Terminal.app setup, so I downloaded iTerm2 and still no luck:
<img width="356" alt="iterm2" src="https://user-images.githubusercontent.com/263494/128777633-a4a8fbc7-5e33-4297-ad1a-59d7bd01e24b.png">
with vim.opt.termguicolors enabled or disabled.
```bash
$ echo $TERM
xterm-256color
```
fwiw

its the same behavior with the jellybeans colorscheme or without.
I even tried opening a new terminals in iterm2 and Terminal.app that do not load my .bash_profile for a fresh environment and still no luck.

I'm struggling to figure out what could be unique about my setup.

**Comment by ajslater** [comment]
Aha. I've got something.

1. Colors do work in iTerm2 when  `vim.opt.termguicolors = true`. I don't think they work at all without `termguicolors`
2. Colors do not work when `colorscheme jellybean` is applied.
3. Colors sometimes work inconsistently. This is very strange behavior. Sometimes only the `up_to_date` color is applied to all virtual text, even the `outdated` text. Its as if a terminal color reset code isn't being set. Other times it does work. It's almost like a caching problem. This is probably what concealed my earlier efforts to debug the problem.

Sad for me because I don't like iTerm2 and Terminal.app's color support sucks.

**Comment by ajslater** [comment]
I suggest putting a warning about `termguicolors` being required to show colors in the README

It would be quite an enhancement for poor stubborn souls like me if you could get it to work with xterm256 colors as well.
And a smoother experience if you changed the defaults to be in [the 256 colors space](https://jonasjacek.github.io/colors/). The closest translations to your defaults are LightSalmon3 (#d7875f) and Grey27 (#444444).

**Comment by vuki656** [comment]
Wow, thanks for digging into this.

I don't really know that much about truecolor/termguicolors/etc... I remember messing with those when I was setting up my nvim config and once I got it working I set it and forgot about it.

I'll have to check if I can in any way detect what color mode is set by the user and adjust the colors accordingly. 

What happens if you set the 256 supported colors through the config?

**Comment by ajslater** [comment]
> What happens if you set the 256 supported colors through the config?
>
The virtual text doesn’t change color unless `termguicolor` is enabled.
Which works fine in a truecolor terminal. Setting that option in a terminal
that doesn’t support truecolor unpredictably breaks the color map and makes
most things unreadable.

>

**Comment by ajslater** [comment]
I think I have a path to a solution

When you highlight the virtual text you use the highlight param `guifg=#hexcode`. I think `guifg` only works with `termguicolor` enabled. The highlight option that works with 256 colors is `ctermfg=colorcode`. e.g.  `ctermfg=136` would be the closest color to your outdated default.

So this would require a more complicated utils.helpers.M.register_highlight_group() that understands what mode to operate in and likely more complicated default options. Like if `termguicolor` is false, use ctermfg.

Unsure when I might get to a patch for this, but at least it's a way forward.

**Comment by vuki656** [comment]
Awesome. This does seem like a possible solitoon.

I'm currently on vacation so my dedicated time for this project is limited but when I get back in qround a week I'll try to fix it.

If you get the time to setup a fix please use the develop branch since I reorganized the whole project there recently.

**Comment by ajslater** [comment]
https://github.com/vuki656/package-info.nvim/pull/42 submitted, with questions
