### ISSUE TITLE
[BUG] Virtual text is displayed for nodes outside of dependencies

### ISSUE THREAD

**Issue by goncharov** [vuki656/package-info.nvim#73]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.5 neovim version

### Neovim Version

NVIM v0.6.0-dev+5fd21b8d3

### Branch

master

### Actual behavior

Virtual text is displayed for nodes outside of `dependencies`

![Screenshot 2021-09-14 at 14 18 05](https://user-images.githubusercontent.com/351309/133248244-c60a3024-c7a4-464d-8114-0c63a03fd1a9.png)

### Expected behavior

Virtual text is displayed only for `dependencies`, `devDependencies` and `peerDependencies`

### Steps to reproduce

Open following package.json
```json
{
  "jest": {
    "verbose": true
  },
  "postcss": {},
  "devDependencies": {
    "jest": "^26.0.0",
    "postcss": "^7.0.0"
  }
}
```

### Package info config

```lua
require "package-info".setup()
```

### Other information

Probably it's happens because it iterates whole buffer and check if key name is matched with dependency name
https://github.com/vuki656/package-info.nvim/blob/master/lua/package-info/modules/core.lua#L195-L196

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by vuki656** [comment]
Thanks for opening an issue. No idea how I didn't encounter that yet. Will fix it soon.

**Comment by vuki656** [comment]
Hey, should be fixed. Let me know if it's still broken.
