### ISSUE TITLE
[BUG] decode error when using url as dependency

### ISSUE THREAD

**Issue by aMOPel** [vuki656/package-info.nvim#82]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.5 neovim version

### Neovim Version

NVIM v0.6.0-dev

### Branch

master

### Actual behavior

Opening a `package.json` with a URL dependency throws an error trying to decode it:

Error:
`.../lua/package-info/libs/json_parser.lua:175: unexpected character '' at line 1 col 1`

https://docs.npmjs.com/cli/v6/configuring-npm/package-json#urls-as-dependencies

### Expected behavior

It's an edge case, but you could catch it and ignore it so the rest still gets parsed.

### Steps to reproduce

The line that broke the parser:
```json
...
  "devDependencies": {
     "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.16",
  }
```

### Package info config

nothing

### Help

No, sorry.

**Comment by vuki656** [comment]
Thanks for opening an issue. Gotta be honest, I've never seen that format. Shouldn't bee to hard to implement.

**Comment by vuki656** [comment]
Unfortunately, I won't be able to support this as it's not natively supported by `npm/yarn` cli.

When I put a package with URL as version and ran `npm outdated --json` I got an error 
![image](https://user-images.githubusercontent.com/8104698/145674996-c6cdbd48-ad0b-4964-9f5a-bf5092be1742.png)
