### ISSUE TITLE
Actions sometimes fail silently 

### ISSUE THREAD

**Issue by vuki656** [vuki656/package-info.nvim#86]
I noticed that sometimes actions like delete/upgrade/install fail silently without anything happening.

Haven't yet been able to reproduce what causes it so if you noticed it and know why it happens, please let me know.

**Comment by mtoohey31** [comment]
Hi @vuki656, I think I may have discovered the issue, could be wrong though, but [here](https://github.com/vuki656/package-info.nvim/blob/0572250a6b69f01416399f2f581aa87c17e03810/lua/package-info/utils.lua#L81) it checks that nothing has been printed to stdout before going ahead with printing errors, which won't be the case if there's been an error in most cases.
