### ISSUE TITLE
[BUG] vim.json requires Neovim HEAD

### ISSUE THREAD

**Issue by delianides** [vuki656/package-info.nvim#88]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.5 neovim version

### Neovim Version

NVIM v0.6.0-dev+557-g5ce35abae Build type: Release LuaJIT 2.1.0-beta3 Compiled by drew@Andrews-MBP-3.localdomain  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-5ce35ab_1/share/nvim"  Run :checkhealth for more info

### Branch

master

### Actual behavior

Received error: `attempt to index field 'json_parser' (a nil value)`

### Expected behavior

Package versions load as virtual text

### Steps to reproduce

Run Neovim 0.5.1, you should see the error. Install Neovim from HEAD 0.6.0-dev and the plugin works fine.

### Package info config

`{ package_manager = "npm" ]`

### Other information

Not sure if its desired to force users to run Neovim from HEAD since 0.5 has shipped. It might make more sense to version check and just fallback to the previous json parser.

### Help

Yes

**Comment by delianides** [comment]
@mhartington #84

**Comment by vuki656** [comment]
My bad for not checking if it's compatible with 0.5 will make sure in future PRs.

I'll merge #84 as soon as the build passes.

**Comment by alxndr** [comment]
Ah, is this why I'm seeing an error after updating?

    .../paqs/start/package-info.nvim/lua/package-info/utils.lua:93: attempt to index upvalue 'json_parser' (a nil value)

**Comment by vuki656** [comment]
> Ah, is this why I'm seeing an error after updating?
> 
> ```
> .../paqs/start/package-info.nvim/lua/package-info/utils.lua:93: attempt to index upvalue 'json_parser' (a nil value)
> ```

Yup, just waiting on Mike to fix the build, and will be merged.
