### ISSUE TITLE
[BUG] Buffer reload triggers show again when autostart is enabled

### ISSUE THREAD

**Issue by mtoohey31** [vuki656/package-info.nvim#90]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.5 neovim version

### Neovim Version

v0.5.1

### Branch

master

### Actual behavior

The `:e` command [here](https://github.com/vuki656/package-info.nvim/blob/0572250a6b69f01416399f2f581aa87c17e03810/lua/package-info/modules/core.lua#L178) triggers the autocommand [here](https://github.com/vuki656/package-info.nvim/blob/0572250a6b69f01416399f2f581aa87c17e03810/lua/package-info/config.lua#L107) when autostart is enabled leading to the buffer being reloaded multiple times.

### Expected behavior

Show should not be triggered again if it is already running.

### Steps to reproduce

First, enable autostart. If you throw print statements at the start of the `show` command (maybe with something like `os.clock()` appeneded so you can see changes between multiple occurrences), you'll see that it runs multiple times after entering a buffer.

### Package info config

```lua
require("package-info").setup()
```

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

There's probably multiple ways to do this, not sure what's best, we could maybe set some kind of global variable and check if it's set before running the show command when entering a buffer. If I swap `:e` to `:noa e` (which disables the trigger of autocommands), the `show` command is only run once, but this prevents other plugins that rely on autocommands from working, so that's not a feasible solution.

**Comment by mtoohey31** [comment]
Actually the fix may be simpler than I thought, is there any need to reload the buffer [here](https://github.com/vuki656/package-info.nvim/blob/037bedfa881d60f0ece93c31f31d04cf3ca29a87/lua/package-info/modules/core.lua#L282) if we're just showing the status? Will `npm` ever update the `package.json` if we're just checking the outdated dependencies?

**Comment by mtoohey31** [comment]
I'm testing the removal of the line above now, if I don't run into any bugs do you want me to open a pull request?

**Comment by vuki656** [comment]
> I'm testing the removal of the line above now, if I don't run into any bugs do you want me to open a pull request?

Sure!
